// Name config for currency ID
module.exports = {
  USD: "United States Dollar",
  CAD: "Canadian Dollar",
  IDR: "Indonesian Rupiah",
  GBP: "Pound sterling",
  CHF: "Swiss Franc",
  SGD: "Singapore Dollar",
  INR: "Indian Rupee",
  MYR: "Malaysian Ringgit",
  JPY: "Japanese Yen",
  KRW: "South Korean Won",
  BGN: "Bulgarian Lev",
  CZK: "Czech Koruna",
  DKK: "Danish Krone",
  HUF: "Hungarian Forint",
  PLN: "Polish Zloty",
  RON: "Romanian Leu",
  SEK: "Swedish Krona",
  ISK: "Icelandic Krona",
  NOK: "Norwegian Krone",
  HRK: "Croatian Kuna",
  RUB: "Russian Ruble",
  TRY: "Turkish Lira",
  AUD: "Australian Dollar",
  BRL: "Brazilian Real",
  CNY: "Chinese Yuan",
  HKD: "Hong Kong Dollar",
  ILS: "Israel Shekel",
  MXN: "Mexican Peso",
  NZD: "New Zealand Dollar",
  PHP: "Philippine Peso",
  THB: "Thai Baht",
  ZAR: "South African Rand",
  EUR: "Euro"
}